apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels:
      app: app2
  replicas: 4
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 80