apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  selector:
    matchLabels:
      app: app3
  replicas: 4
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 660
